data.raw["capsule"]["raw-fish"].fuel_category = "fish-fuel"
data.raw["capsule"]["raw-fish"].fuel_value = "10MJ"
data.raw["pipe"]["pipe"].next_upgrade = "steel-pipe"
data.raw["pipe-to-ground"]["pipe-to-ground"].next_upgrade = "steel-pipe-to-ground"
data.raw["storage-tank"]["storage-tank"].next_upgrade = "steel-storage-tank"